int ML24_DaysInMonth(int y,int m){if(m==2)return ((y%4==0&&y%100!=0)||y%400==0)?29:28;if(m==4||m==6||m==9||m==11)return 30;return 31;}
datetime ML24_NthSundayUTC(int y,int m,int nth,int hour){MqlDateTime d;ZeroMemory(d);d.year=y;d.mon=m;d.day=1;d.hour=hour;datetime t=StructToTime(d);TimeToStruct(t,d);int first=1+((7-d.day_of_week)%7);d.day=first+7*(nth-1);return StructToTime(d);}
datetime ML24_LastSundayUTC(int y,int m,int hour){MqlDateTime d;ZeroMemory(d);d.year=y;d.mon=m;d.day=ML24_DaysInMonth(y,m);d.hour=hour;datetime t=StructToTime(d);TimeToStruct(t,d);d.day-=d.day_of_week;return StructToTime(d);}
bool ML24_UKSummer(datetime utc){MqlDateTime d;TimeToStruct(utc,d);return utc>=ML24_LastSundayUTC(d.year,3,1)&&utc<ML24_LastSundayUTC(d.year,10,1);}
bool ML24_USSummer(datetime utc){MqlDateTime d;TimeToStruct(utc,d);return utc>=ML24_NthSundayUTC(d.year,3,2,7)&&utc<ML24_NthSundayUTC(d.year,11,1,6);}
datetime ML24_ServerToUTC(datetime st){datetime sn=TimeTradeServer();if(sn<=0)sn=TimeCurrent();datetime un=TimeGMT();if(un<=0)return st;return (datetime)((long)st-(long)(sn-un));}
datetime ML24_TodayUTCStart(datetime nowUtc,int hour,int minute){MqlDateTime d;TimeToStruct(nowUtc,d);d.hour=hour;d.min=minute;d.sec=0;return StructToTime(d);}
bool ML24_ORBounds(MqlRates &r[],datetime startUtc,int minutes,double &hi,double &lo){datetime endUtc=startUtc+minutes*60;bool any=false;hi=-DBL_MAX;lo=DBL_MAX;for(int i=1;i<ArraySize(r);i++){datetime t=ML24_ServerToUTC(r[i].time);if(t<startUtc||t>=endUtc)continue;hi=MathMax(hi,r[i].high);lo=MathMin(lo,r[i].low);any=true;}return any&&hi>lo&&hi!=-DBL_MAX&&lo!=DBL_MAX;}
bool ML24_BuildORBSession(MqlRates &r[],double a,bool buy,datetime startUtc,string name,Signal &sig)
{
   datetime nowUtc=TimeGMT();if(nowUtc<=0)return false;datetime endUtc=startUtc+OpeningRangeMinutes*60;if(nowUtc<endUtc||nowUtc>endUtc+ORBMaxMinutesAfterOpen*60)return false;
   double orHi,orLo;if(!ML24_ORBounds(r,startUtc,OpeningRangeMinutes,orHi,orLo))return false;int br=-1;double buf=MathMax(_Point*5,a*0.05);
   for(int i=ArraySize(r)-2;i>=3;i--){datetime t=ML24_ServerToUTC(r[i].time);if(t<endUtc||t>nowUtc)continue;bool broke=buy?(r[i].close>orHi+buf):(r[i].close<orLo-buf);if(broke&&StrongDisp(r,i,a,ORBMinBreakATR,buy)){br=i;break;}}
   if(br<3)return false;double boundary=buy?orHi:orLo,band=MathMax(_Point*5,a*ORBRetestBandATR);int ret=-1;
   for(int i=br-1;i>=2;i--){datetime t=ML24_ServerToUTC(r[i].time);if(t<endUtc)continue;bool touch=buy?(r[i].low<=boundary+band&&r[i].close>=boundary-band):(r[i].high>=boundary-band&&r[i].close<=boundary+band);if(touch){ret=i;break;}}
   if(ret<2||!ML24_DirectionalResume(r,buy,a,0.18))return false;double inv=buy?r[ret].low:r[ret].high;for(int i=ret;i>=1;i--){if(buy)inv=MathMin(inv,r[i].low);else inv=MathMax(inv,r[i].high);}
   double lo=boundary-band,hi=boundary+band;sig.valid=true;sig.buy=buy;sig.reentry=true;sig.flip=false;sig.anchor_idx=ret;sig.break_idx=br;sig.pd_idx=ret;sig.anchor_price=inv;sig.break_level=boundary;sig.impulse_extreme=buy?r[br].high:r[br].low;sig.ote_low=lo;sig.ote_high=hi;sig.pd_low=lo;sig.pd_high=hi;sig.entry_low=lo;sig.entry_high=hi;sig.pd_type=name+"_ORB_RETEST";return true;
}
bool ML24_BuildORB(MqlRates &r[],double a,bool buy,Signal &sig){datetime nowUtc=TimeGMT();if(nowUtc<=0)return false;datetime lon=ML24_TodayUTCStart(nowUtc,ML24_UKSummer(nowUtc)?7:8,0),ny=ML24_TodayUTCStart(nowUtc,ML24_USSummer(nowUtc)?12:13,20);if(ML24_BuildORBSession(r,a,buy,ny,"NY",sig))return true;return ML24_BuildORBSession(r,a,buy,lon,"LONDON",sig);}

bool ML24_EntryValue(Signal &sig,MqlTick &tk,double a){if(!sig.valid)return false;double entry=sig.buy?tk.ask:tk.bid;return EntryAtValue(sig.buy,entry,sig,a);}
double ML24_ZoneDistance(double mid){if(mid<g_plan.zone_low)return g_plan.zone_low-mid;if(mid>g_plan.zone_high)return mid-g_plan.zone_high;return 0;}

void ML24_SendCandidate(string model,string role,bool buy,bool flipBranch,Signal &sig,bool pattern,bool eligible,string reasons,bool zoneContext,bool recentZone,bool cloudAllowed,bool localAllowed,bool priorityBlocked,MqlRates &r[],double a,MqlTick &tk,datetime barTs)
{
   double entry=buy?tk.ask:tk.bid,sl=0,t1=0,t2=0,t3=0;if(pattern){sl=buy?sig.anchor_price-a*SLBufferATR:sig.anchor_price+a*SLBufferATR;}
   if(flipBranch){t1=g_plan.flip_t1;t2=g_plan.flip_t2;t3=g_plan.flip_t3;}else{t1=g_plan.original_t1;t2=g_plan.original_t2;t3=g_plan.original_t3;}
   entry=NormalizeDouble(entry,_Digits);sl=NormalizeDouble(sl,_Digits);
   double point=_Point>0?_Point:0.01,spread=(tk.ask-tk.bid)/point,mid=(tk.ask+tk.bid)/2.0,zoneDist=(a>0?ML24_ZoneDistance(mid)/a:0),eff=ML24_Efficiency(r,24),fast=ATR(r,7,1),slow=ATR(r,28,1),vr=slow>0?fast/slow:0,vwap=ML24_VWAP(r,1,VWAPLookbackBars),vwapDist=(a>0&&vwap>0)?MathAbs(mid-vwap)/a:0;
   double dispRangeAtr=0,dispBodyAtr=0,dispBodyFraction=0;if(pattern&&sig.break_idx>=1&&sig.break_idx<ArraySize(r)){double range=r[sig.break_idx].high-r[sig.break_idx].low,body=MathAbs(r[sig.break_idx].close-r[sig.break_idx].open);dispRangeAtr=a>0?range/a:0;dispBodyAtr=a>0?body/a:0;dispBodyFraction=range>0?body/range:0;}
   string runtimeVer=ML24_ReadState("version"),lastModel=ML24_ReadState("last_execution_model");int rp=ML24_StateInt("primary_entries"),rr=ML24_StateInt("reentries"),rfp=ML24_StateInt("flip_primary_entries"),rfr=ML24_StateInt("flip_reentries"),ropen=ML24_StateInt("open_positions");
   datetime candidateTs=TimeTradeServer();if(candidateTs<=0)candidateTs=TimeCurrent();
   string cid="MT5_324|"+g_plan.analysis_id+"|"+g_plan.zone_id+"|"+model+"|"+role+"|"+IntegerToString((int)barTs);
   string features=StringFormat("{\"observation_only\":1,\"execution_authority\":0,\"closed_m1_bar_open_ts\":%I64d,\"role\":\"%s\",\"pattern_valid\":%d,\"zone_context\":%d,\"recent_zone_interaction\":%d,\"cloud_model_allowed\":%d,\"local_regime_allowed\":%d,\"priority_blocked\":%d,\"live_block\":%d,\"live_block_reason\":\"%s\",\"cloud_regime\":\"%s\",\"local_regime\":\"%s\",\"setup_type\":\"%s\",\"grade\":\"%s\",\"zone_state\":\"%s\",\"spread_points\":%.2f,\"zone_distance_atr\":%.5f,\"efficiency\":%.5f,\"volatility_ratio\":%.5f,\"vwap_proxy\":%.5f,\"vwap_distance_atr\":%.5f,\"signal_pd_type\":\"%s\",\"break_level\":%.5f,\"impulse_extreme\":%.5f,\"ote_low\":%.5f,\"ote_high\":%.5f,\"pd_low\":%.5f,\"pd_high\":%.5f,\"displacement_range_atr\":%.5f,\"displacement_body_atr\":%.5f,\"displacement_body_fraction\":%.5f,\"runtime_sequence_version\":\"%s\",\"runtime_primary_entries\":%d,\"runtime_reentries\":%d,\"runtime_flip_primary_entries\":%d,\"runtime_flip_reentries\":%d,\"runtime_open_positions\":%d,\"runtime_last_execution_model\":\"%s\"}",(long)barTs,ML24_Escape(role),pattern?1:0,zoneContext?1:0,recentZone?1:0,cloudAllowed?1:0,localAllowed?1:0,priorityBlocked?1:0,ml24_live_block?1:0,ML24_Escape(ml24_live_block_reason),ML24_Escape(ml24_cloud_regime),ML24_Escape(ML24_LocalRegime(r)),ML24_Escape(g_plan.setup_type),ML24_Escape(g_plan.grade),ML24_Escape(g_plan.zone_state),spread,zoneDist,eff,vr,vwap,vwapDist,ML24_Escape(pattern?sig.pd_type:""),pattern?sig.break_level:0,pattern?sig.impulse_extreme:0,pattern?sig.ote_low:0,pattern?sig.ote_high:0,pattern?sig.pd_low:0,pattern?sig.pd_high:0,dispRangeAtr,dispBodyAtr,dispBodyFraction,ML24_Escape(runtimeVer),rp,rr,rfp,rfr,ropen,ML24_Escape(lastModel));
   string details=StringFormat("{\"candidate_id\":\"%s\",\"ts\":%I64d,\"source\":\"MT5_EXECUTION\",\"source_version\":\"%s\",\"analysis_id\":\"%s\",\"zone_id\":\"%s\",\"model\":\"%s\",\"direction\":\"%s\",\"eligible\":%s,\"rejection_reasons\":[%s],\"entry_price\":%.5f,\"stop_price\":%.5f,\"target1\":%.5f,\"target2\":%.5f,\"target3\":%.5f,\"atr\":%.5f,\"regime\":\"%s\",\"features\":%s}",ML24_Escape(cid),(long)candidateTs,ML24_VERSION,ML24_Escape(g_plan.analysis_id),ML24_Escape(g_plan.zone_id),ML24_Escape(model),buy?"BUY":"SELL",ML24_Bool(eligible),reasons,entry,sl,t1,t2,t3,a,ML24_Escape(ML24_LocalRegime(r)),features);
   string body=StringFormat("{\"ts\":%I64d,\"event\":\"ML_CANDIDATE\",\"analysis_id\":\"%s\",\"zone_id\":\"%s\",\"price\":%.5f,\"details\":%s}",(long)candidateTs,ML24_Escape(g_plan.analysis_id),ML24_Escape(g_plan.zone_id),entry,details);
   string response;if(ML24_Post("/mt5/feedback",body,response))ml24_packets_sent++;
}
