#property strict
#property version   "3.23"
#property description "DEMO/PAPER XAU M1 V6.3: SMC location + regime + ICT sniper + momentum/VWAP/ORB complementary execution."

#define Evaluate TZ_SeqCore_Evaluate
#define OnInit TZ_SeqCore_OnInit
#define OnDeinit TZ_SeqCore_OnDeinit
#define OnTimer TZ_SeqCore_OnTimer
#define OnTick TZ_SeqCore_OnTick
#include <TradeZoneCore\InstitutionalSMC_SequenceEA_v3_21_Flip_Reentry_Backtest_Demo.mq5>
#undef Evaluate
#undef OnInit
#undef OnDeinit
#undef OnTimer
#undef OnTick

#define TZ_SEQUENCE_VERSION "3.23"

input bool EnableAlternativePrimary=true;
input bool EnableMomentumPullbackModel=true;
input bool EnableVWAPProxyModel=true;
input bool EnableOpeningRangeRetestModel=true;
input double AltModelRiskMultiplier=0.75;
input double MomentumRetraceMin=0.30;
input double MomentumRetraceMax=0.60;
input double VWAPBandATR=0.15;
input int VWAPLookbackBars=60;
input int OpeningRangeMinutes=30;
input int ORBMaxMinutesAfterOpen=240;
input double ORBRetestBandATR=0.12;
input double ORBMinBreakATR=0.55;
input int AlternativeZoneInteractionBars=120;

datetime g_tzLastStateWrite=0,g_tzLastHeartbeat=0;
string g_tzLoadedStateKey="",g_tzExtAnalysisId="",g_tzCloudRegime="UNKNOWN",g_tzLastLocalRegime="UNKNOWN",g_tzLastModel="";
bool g_tzAllowMomentum=false,g_tzAllowVWAP=false,g_tzAllowORB=false;

string TZ_JsonEscape(string s){StringReplace(s,"\\","\\\\");StringReplace(s,"\"","\\\"");StringReplace(s,"\r"," ");StringReplace(s,"\n"," ");return s;}
string TZ_ReadLocalKV(string fileName,string key){int h=FileOpen("TradeZone\\"+fileName,FILE_READ|FILE_TXT|FILE_ANSI);if(h==INVALID_HANDLE)return "";string needle=key+"=",value="";while(!FileIsEnding(h)){string line=FileReadString(h);if(StringFind(line,needle)==0){value=StringSubstr(line,StringLen(needle));break;}}FileClose(h);StringTrimLeft(value);StringTrimRight(value);return value;}
bool TZ_TextFlag(string text,string key,bool def=false){string v=KV(text,key);if(v=="")return def;StringToLower(v);return (v=="1"||v=="true"||v=="yes"||v=="on");}
uint TZ_Hash(string s){uint h=2166136261;for(int i=0;i<StringLen(s);i++){h^=(uint)StringGetCharacter(s,i);h*=16777619;}return h;}
string TZ_StatePrefix(){if(g_plan.analysis_id=="")return "";string seed=g_plan.analysis_id+"|"+g_plan.zone_id;return "TZ."+IntegerToString((int)AccountInfoInteger(ACCOUNT_LOGIN))+"."+_Symbol+"."+IntegerToString((int)TZ_Hash(seed));}
int TZ_OpenPositionCount(){int n=0;for(int i=PositionsTotal()-1;i>=0;i--){ulong t=PositionGetTicket(i);if(!t)continue;if(PositionGetString(POSITION_SYMBOL)==_Symbol&&(ulong)PositionGetInteger(POSITION_MAGIC)==MagicNumber)n++;}return n;}
void TZ_LoadPersistentState(){string p=TZ_StatePrefix();if(p==""||p==g_tzLoadedStateKey)return;g_tzLoadedStateKey=p;if(GlobalVariableCheck(p+".P"))g_primaryEntries=(int)GlobalVariableGet(p+".P");if(GlobalVariableCheck(p+".R"))g_reentries=(int)GlobalVariableGet(p+".R");if(GlobalVariableCheck(p+".FP"))g_flipPrimaryEntries=(int)GlobalVariableGet(p+".FP");if(GlobalVariableCheck(p+".FR"))g_flipReentries=(int)GlobalVariableGet(p+".FR");if(GlobalVariableCheck(p+".BAR"))g_lastTradeBar=(datetime)GlobalVariableGet(p+".BAR");if(GlobalVariableCheck(p+".FLIP"))g_flipCandidate=(GlobalVariableGet(p+".FLIP")>0.5);if(GlobalVariableCheck(p+".FAT"))g_flipAcceptedAt=(datetime)GlobalVariableGet(p+".FAT");}
void TZ_SavePersistentState(){string p=TZ_StatePrefix();if(p=="")return;GlobalVariableSet(p+".P",(double)g_primaryEntries);GlobalVariableSet(p+".R",(double)g_reentries);GlobalVariableSet(p+".FP",(double)g_flipPrimaryEntries);GlobalVariableSet(p+".FR",(double)g_flipReentries);GlobalVariableSet(p+".BAR",(double)g_lastTradeBar);GlobalVariableSet(p+".FLIP",g_flipCandidate?1.0:0.0);GlobalVariableSet(p+".FAT",(double)g_flipAcceptedAt);}

bool TZ_Post(string path,string body,string &response){if(CloudApiKey=="")return false;string url=CloudBaseUrl+path;string headers="Content-Type: application/json\r\nX-API-Key: "+CloudApiKey+"\r\n";char data[],result[];string rh;StringToCharArray(body,data,0,WHOLE_ARRAY,CP_UTF8);if(ArraySize(data)>0)ArrayResize(data,ArraySize(data)-1);ResetLastError();int code=WebRequest("POST",url,headers,HttpTimeoutMs,data,result,rh);response=CharArrayToString(result,0,-1,CP_UTF8);return code==200;}

void TZ_LoadExecutionProfile(){if(g_plan.analysis_id=="")return;if(IsTester()){g_tzCloudRegime="TESTER";g_tzAllowMomentum=EnableMomentumPullbackModel;g_tzAllowVWAP=EnableVWAPProxyModel;g_tzAllowORB=EnableOpeningRangeRetestModel;g_tzExtAnalysisId=g_plan.analysis_id;return;}if(g_tzExtAnalysisId==g_plan.analysis_id)return;string text;if(!HttpGet("/mt5/plan",text))return;if(KV(text,"analysis_id")!=g_plan.analysis_id)return;g_tzCloudRegime=KV(text,"market_regime");if(g_tzCloudRegime=="")g_tzCloudRegime="UNKNOWN";g_tzAllowMomentum=EnableMomentumPullbackModel&&TZ_TextFlag(text,"model_momentum_pullback",false);g_tzAllowVWAP=EnableVWAPProxyModel&&TZ_TextFlag(text,"model_vwap_proxy_reclaim",false);g_tzAllowORB=EnableOpeningRangeRetestModel&&TZ_TextFlag(text,"model_opening_range_retest",false);g_tzExtAnalysisId=g_plan.analysis_id;Print("TradeZone V6.3 execution profile: regime=",g_tzCloudRegime," momentum=",g_tzAllowMomentum," vwap=",g_tzAllowVWAP," orb=",g_tzAllowORB);}

double TZ_Efficiency(MqlRates &r[],int n){n=MathMin(n,ArraySize(r)-2);if(n<3)return 0;double path=0;for(int i=1;i<=n;i++)path+=MathAbs(r[i].close-r[i+1].close);if(path<=0)return 0;return MathMin(1.0,MathAbs(r[1].close-r[n+1].close)/path);}
string TZ_LocalRegime(MqlRates &r[]){if(ArraySize(r)<80)return "UNKNOWN";double fast=ATR(r,7,1),slow=ATR(r,28,1),eff=TZ_Efficiency(r,24);if(fast<=0||slow<=0)return "UNKNOWN";double vr=fast/slow;if(vr>=1.45&&eff<=0.28)return "EXHAUSTION";if(vr>=1.22&&eff>=0.34)return "EXPANSION";if(vr<=0.76)return "COMPRESSION";if(eff>=0.46)return "TREND";return "RANGE";}
bool TZ_RegimeAllows(string model,string localRegime){if(model=="MOMENTUM")return g_tzAllowMomentum&&(localRegime=="TREND"||localRegime=="EXPANSION");if(model=="VWAP")return g_tzAllowVWAP&&localRegime=="TREND";if(model=="ORB")return g_tzAllowORB&&(localRegime=="TREND"||localRegime=="EXPANSION");return false;}
bool TZ_RecentZoneInteraction(MqlRates &r[],int bars){int n=MathMin(bars,ArraySize(r)-2);for(int i=1;i<=n;i++)if(r[i].high>=g_plan.zone_low&&r[i].low<=g_plan.zone_high)return true;return false;}
bool TZ_DirectionalResume(MqlRates &r[],bool buy,double a,double minBodyATR=0.20){if(ArraySize(r)<4||a<=0)return false;double body=MathAbs(r[1].close-r[1].open);if(body<minBodyATR*a)return false;if(buy)return r[1].close>r[1].open&&r[1].close>r[2].high;return r[1].close<r[1].open&&r[1].close<r[2].low;}

bool TZ_BuildMomentumPullback(MqlRates &r[],double a,bool buy,Signal &sig){sig.valid=false;if(ArraySize(r)<90||a<=0)return false;int mx=MathMin(45,ArraySize(r)-8);double rmin=MathMin(MomentumRetraceMin,MomentumRetraceMax),rmax=MathMax(MomentumRetraceMin,MomentumRetraceMax);for(int br=4;br<=mx;br++){int bp=-1;double bos=0;if(!OlderPivot(r,br+2,MathMin(br+35,ArraySize(r)-3),buy,bp,bos))continue;bool broke=buy?(r[br].close>bos):(r[br].close<bos);if(!broke||!StrongDisp(r,br,a,MathMax(0.65,ReentryDisplacementATR*0.80),buy))continue;int ap=-1;double impulseAnchor=0;if(!OlderPivot(r,br+2,MathMin(br+45,ArraySize(r)-3),!buy,ap,impulseAnchor))continue;double imp=buy?r[br].high:r[br].low;for(int j=br;j>=1;j--){if(buy)imp=MathMax(imp,r[j].high);else imp=MathMin(imp,r[j].low);}double d=MathAbs(imp-impulseAnchor);if(d<a)continue;double lo,hi;if(buy){lo=imp-d*rmax;hi=imp-d*rmin;}else{lo=imp+d*rmin;hi=imp+d*rmax;}if(lo>hi){double x=lo;lo=hi;hi=x;}bool touched=false;double inv=buy?DBL_MAX:-DBL_MAX;for(int i=1;i<br;i++){if(r[i].high>=lo&&r[i].low<=hi)touched=true;if(buy)inv=MathMin(inv,r[i].low);else inv=MathMax(inv,r[i].high);}if(!touched||!TZ_DirectionalResume(r,buy,a,0.20))continue;if(inv==DBL_MAX||inv==-DBL_MAX)continue;sig.valid=true;sig.buy=buy;sig.reentry=true;sig.flip=false;sig.anchor_idx=ap;sig.break_idx=br;sig.pd_idx=1;sig.anchor_price=inv;sig.break_level=bos;sig.impulse_extreme=imp;sig.ote_low=lo;sig.ote_high=hi;sig.pd_low=lo;sig.pd_high=hi;sig.entry_low=lo;sig.entry_high=hi;sig.pd_type="MOM_PULLBACK";return true;}return false;}

double TZ_VWAP(MqlRates &r[],int start,int count){int end=MathMin(start+count,ArraySize(r));if(start<0||start>=end)return 0;double pv=0,w=0;for(int i=start;i<end;i++){double wt=(double)r[i].tick_volume;if(wt<=0)wt=1.0;double tp=(r[i].high+r[i].low+r[i].close)/3.0;pv+=tp*wt;w+=wt;}return w>0?pv/w:0;}
bool TZ_BuildVWAPReclaim(MqlRates &r[],double a,bool buy,Signal &sig){sig.valid=false;if(ArraySize(r)<VWAPLookbackBars+40||a<=0)return false;int half=MathMax(20,VWAPLookbackBars/2);double recent=TZ_VWAP(r,1,VWAPLookbackBars),old=TZ_VWAP(r,1+half,VWAPLookbackBars);if(recent<=0||old<=0)return false;if(buy&&recent<=old)return false;if(!buy&&recent>=old)return false;double band=MathMax(_Point*5,a*VWAPBandATR),lo=recent-band,hi=recent+band;bool touched=false;for(int i=2;i<=MathMin(10,ArraySize(r)-2);i++)if(r[i].high>=lo&&r[i].low<=hi){touched=true;break;}if(!touched||!TZ_DirectionalResume(r,buy,a,0.18))return false;if(buy&&r[1].close<=recent)return false;if(!buy&&r[1].close>=recent)return false;double inv=buy?r[1].low:r[1].high;for(int i=1;i<=MathMin(12,ArraySize(r)-2);i++){if(buy)inv=MathMin(inv,r[i].low);else inv=MathMax(inv,r[i].high);}sig.valid=true;sig.buy=buy;sig.reentry=true;sig.flip=false;sig.anchor_idx=12;sig.break_idx=1;sig.pd_idx=1;sig.anchor_price=inv;sig.break_level=recent;sig.impulse_extreme=r[1].close;sig.ote_low=lo;sig.ote_high=hi;sig.pd_low=lo;sig.pd_high=hi;sig.entry_low=lo;sig.entry_high=hi;sig.pd_type="VWAP_PROXY_RECLAIM";return true;}

int TZ_DaysInMonth(int year,int mon){if(mon==2)return ((year%4==0&&year%100!=0)||year%400==0)?29:28;if(mon==4||mon==6||mon==9||mon==11)return 30;return 31;}
datetime TZ_NthSundayUTC(int year,int mon,int nth,int hour){MqlDateTime d;ZeroMemory(d);d.year=year;d.mon=mon;d.day=1;d.hour=hour;datetime t=StructToTime(d);TimeToStruct(t,d);int first=1+((7-d.day_of_week)%7);d.day=first+7*(nth-1);return StructToTime(d);}
datetime TZ_LastSundayUTC(int year,int mon,int hour){MqlDateTime d;ZeroMemory(d);d.year=year;d.mon=mon;d.day=TZ_DaysInMonth(year,mon);d.hour=hour;datetime t=StructToTime(d);TimeToStruct(t,d);d.day-=d.day_of_week;return StructToTime(d);}
bool TZ_UKSummer(datetime utc){MqlDateTime d;TimeToStruct(utc,d);datetime st=TZ_LastSundayUTC(d.year,3,1),en=TZ_LastSundayUTC(d.year,10,1);return utc>=st&&utc<en;}
bool TZ_USSummer(datetime utc){MqlDateTime d;TimeToStruct(utc,d);datetime st=TZ_NthSundayUTC(d.year,3,2,7),en=TZ_NthSundayUTC(d.year,11,1,6);return utc>=st&&utc<en;}
datetime TZ_ServerToUTC(datetime serverTime){datetime serverNow=TimeTradeServer();if(serverNow<=0)serverNow=TimeCurrent();datetime utcNow=TimeGMT();if(utcNow<=0)return serverTime;long offset=(long)(serverNow-utcNow);return (datetime)((long)serverTime-offset);}
datetime TZ_TodayUTCStart(datetime nowUtc,int hour,int minute){MqlDateTime d;TimeToStruct(nowUtc,d);d.hour=hour;d.min=minute;d.sec=0;return StructToTime(d);}
bool TZ_ORBounds(MqlRates &r[],datetime startUtc,int minutes,double &hi,double &lo){datetime endUtc=startUtc+minutes*60;bool any=false;hi=-DBL_MAX;lo=DBL_MAX;for(int i=1;i<ArraySize(r);i++){datetime t=TZ_ServerToUTC(r[i].time);if(t<startUtc||t>=endUtc)continue;hi=MathMax(hi,r[i].high);lo=MathMin(lo,r[i].low);any=true;}return any&&hi>lo&&hi!=-DBL_MAX&&lo!=DBL_MAX;}
bool TZ_BuildORBSession(MqlRates &r[],double a,bool buy,datetime startUtc,string name,Signal &sig){datetime nowUtc=TimeGMT();if(nowUtc<=0)return false;datetime endUtc=startUtc+OpeningRangeMinutes*60;if(nowUtc<endUtc||nowUtc>endUtc+ORBMaxMinutesAfterOpen*60)return false;double orHi,orLo;if(!TZ_ORBounds(r,startUtc,OpeningRangeMinutes,orHi,orLo))return false;int br=-1;double buf=MathMax(_Point*5,a*0.05);for(int i=ArraySize(r)-2;i>=3;i--){datetime t=TZ_ServerToUTC(r[i].time);if(t<endUtc||t>nowUtc)continue;bool broke=buy?(r[i].close>orHi+buf):(r[i].close<orLo-buf);if(broke&&StrongDisp(r,i,a,ORBMinBreakATR,buy)){br=i;break;}}if(br<3)return false;double boundary=buy?orHi:orLo,band=MathMax(_Point*5,a*ORBRetestBandATR);int ret=-1;for(int i=br-1;i>=2;i--){datetime t=TZ_ServerToUTC(r[i].time);if(t<endUtc)continue;bool touch=buy?(r[i].low<=boundary+band&&r[i].close>=boundary-band):(r[i].high>=boundary-band&&r[i].close<=boundary+band);if(touch){ret=i;break;}}if(ret<2||!TZ_DirectionalResume(r,buy,a,0.18))return false;double inv=buy?r[ret].low:r[ret].high;for(int i=ret;i>=1;i--){if(buy)inv=MathMin(inv,r[i].low);else inv=MathMax(inv,r[i].high);}double lo=boundary-band,hi=boundary+band;sig.valid=true;sig.buy=buy;sig.reentry=true;sig.flip=false;sig.anchor_idx=ret;sig.break_idx=br;sig.pd_idx=ret;sig.anchor_price=inv;sig.break_level=boundary;sig.impulse_extreme=buy?r[br].high:r[br].low;sig.ote_low=lo;sig.ote_high=hi;sig.pd_low=lo;sig.pd_high=hi;sig.entry_low=lo;sig.entry_high=hi;sig.pd_type=name+"_ORB_RETEST";return true;}
bool TZ_BuildOpeningRangeRetest(MqlRates &r[],double a,bool buy,Signal &sig){datetime nowUtc=TimeGMT();if(nowUtc<=0)return false;bool ukSummer=TZ_UKSummer(nowUtc),usSummer=TZ_USSummer(nowUtc);datetime london=TZ_TodayUTCStart(nowUtc,ukSummer?7:8,0),ny=TZ_TodayUTCStart(nowUtc,usSummer?12:13,20);if(TZ_BuildORBSession(r,a,buy,ny,"NY",sig))return true;return TZ_BuildORBSession(r,a,buy,london,"LONDON",sig);}

void TZ_WriteSequenceState(){if(IsTester())return;datetime now=TimeTradeServer();if(now<=0)now=TimeCurrent();if(now-g_tzLastStateWrite<5)return;g_tzLastStateWrite=now;int openCount=TZ_OpenPositionCount();bool safe=(openCount==0);FolderCreate("TradeZone");int h=FileOpen("TradeZone\\sequence_state.txt",FILE_WRITE|FILE_TXT|FILE_ANSI);if(h==INVALID_HANDLE)return;FileWriteString(h,"ts="+IntegerToString((int)now)+"\r\n");FileWriteString(h,"version="+TZ_SEQUENCE_VERSION+"\r\n");FileWriteString(h,"restart_safe="+(safe?"1":"0")+"\r\n");FileWriteString(h,"active_sequence="+(openCount>0?"1":"0")+"\r\n");FileWriteString(h,"open_positions="+IntegerToString(openCount)+"\r\n");FileWriteString(h,"analysis_id="+g_plan.analysis_id+"\r\n");FileWriteString(h,"zone_id="+g_plan.zone_id+"\r\n");FileWriteString(h,"plan_valid="+(g_plan.valid?"1":"0")+"\r\n");FileWriteString(h,"cloud_regime="+g_tzCloudRegime+"\r\n");FileWriteString(h,"local_regime="+g_tzLastLocalRegime+"\r\n");FileWriteString(h,"last_execution_model="+g_tzLastModel+"\r\n");FileWriteString(h,"primary_entries="+IntegerToString(g_primaryEntries)+"\r\n");FileWriteString(h,"reentries="+IntegerToString(g_reentries)+"\r\n");FileWriteString(h,"flip_primary_entries="+IntegerToString(g_flipPrimaryEntries)+"\r\n");FileWriteString(h,"flip_reentries="+IntegerToString(g_flipReentries)+"\r\n");FileClose(h);}
void TZ_SendSequenceHeartbeat(){if(IsTester()||OperatingMode!=LIVE_CLOUD)return;datetime now=TimeTradeServer();if(now<=0)now=TimeCurrent();if(now-g_tzLastHeartbeat<15)return;g_tzLastHeartbeat=now;int openCount=TZ_OpenPositionCount();bool safe=(openCount==0);string updater=TZ_ReadLocalKV("updater_status.txt","updater_version"),stable=TZ_ReadLocalKV("updater_status.txt","stable_release"),installedBridge=TZ_ReadLocalKV("updater_status.txt","installed_bridge_version"),installedSequence=TZ_ReadLocalKV("updater_status.txt","installed_sequence_version"),desiredBridge=TZ_ReadLocalKV("updater_status.txt","desired_bridge_version"),desiredSequence=TZ_ReadLocalKV("updater_status.txt","desired_sequence_version"),pending=TZ_ReadLocalKV("updater_status.txt","pending_reload"),updateResult=TZ_ReadLocalKV("updater_status.txt","result");string body=StringFormat("{\"ts\":%I64d,\"ea\":\"InstitutionalSMC_SequenceEA\",\"version\":\"%s\",\"symbol\":\"%s\",\"account_login\":%I64d,\"details\":{\"paper_only\":true,\"restart_safe\":%s,\"active_sequence\":%s,\"open_positions\":%d,\"state_persisted\":true,\"analysis_id\":\"%s\",\"zone_id\":\"%s\",\"plan_valid\":%s,\"cloud_regime\":\"%s\",\"local_regime\":\"%s\",\"last_execution_model\":\"%s\",\"primary_entries\":%d,\"reentries\":%d,\"flip_primary_entries\":%d,\"flip_reentries\":%d,\"updater_version\":\"%s\",\"stable_release\":\"%s\",\"installed_bridge_version\":\"%s\",\"installed_sequence_version\":\"%s\",\"desired_bridge_version\":\"%s\",\"desired_sequence_version\":\"%s\",\"pending_reload\":\"%s\",\"update_result\":\"%s\"}}",(long)now,TZ_SEQUENCE_VERSION,TZ_JsonEscape(_Symbol),(long)AccountInfoInteger(ACCOUNT_LOGIN),safe?"true":"false",openCount>0?"true":"false",openCount,TZ_JsonEscape(g_plan.analysis_id),TZ_JsonEscape(g_plan.zone_id),g_plan.valid?"true":"false",TZ_JsonEscape(g_tzCloudRegime),TZ_JsonEscape(g_tzLastLocalRegime),TZ_JsonEscape(g_tzLastModel),g_primaryEntries,g_reentries,g_flipPrimaryEntries,g_flipReentries,TZ_JsonEscape(updater),TZ_JsonEscape(stable),TZ_JsonEscape(installedBridge),TZ_JsonEscape(installedSequence),TZ_JsonEscape(desiredBridge),TZ_JsonEscape(desiredSequence),TZ_JsonEscape(pending),TZ_JsonEscape(updateResult));string rr;TZ_Post("/mt5/heartbeat",body,rr);}
void TZ_PreCoreSync(){if(IsTester())return;if(OperatingMode==LIVE_CLOUD)RefreshPlan();TZ_LoadExecutionProfile();TZ_LoadPersistentState();}

bool TZ_TryAlternativePrimary(MqlRates &r[],double a,bool buy,string localRegime,Signal &sig,string &tag){if(!EnableAlternativePrimary||g_plan.setup_type!="CONTINUATION"||!TZ_RecentZoneInteraction(r,AlternativeZoneInteractionBars))return false;if(TZ_RegimeAllows("ORB",localRegime)&&TZ_BuildOpeningRangeRetest(r,a,buy,sig)){sig.reentry=false;tag="OR0";return true;}if(TZ_RegimeAllows("MOMENTUM",localRegime)&&TZ_BuildMomentumPullback(r,a,buy,sig)){sig.reentry=false;tag="MP0";return true;}if(TZ_RegimeAllows("VWAP",localRegime)&&TZ_BuildVWAPReclaim(r,a,buy,sig)){sig.reentry=false;tag="VW0";return true;}return false;}
bool TZ_TryAlternativeReentry(MqlRates &r[],double a,bool buy,string localRegime,Signal &sig,string &tag){if(TZ_RegimeAllows("MOMENTUM",localRegime)&&TZ_BuildMomentumPullback(r,a,buy,sig)){sig.reentry=true;tag="MR"+IntegerToString(g_reentries+1);return true;}if(TZ_RegimeAllows("VWAP",localRegime)&&TZ_BuildVWAPReclaim(r,a,buy,sig)){sig.reentry=true;tag="VR"+IntegerToString(g_reentries+1);return true;}if(TZ_RegimeAllows("ORB",localRegime)&&TZ_BuildOpeningRangeRetest(r,a,buy,sig)){sig.reentry=true;tag="ORR"+IntegerToString(g_reentries+1);return true;}return false;}

void Evaluate(){if(!RefreshPlan()||!RiskGuards())return;TZ_LoadExecutionProfile();if(EnableZoneFlip&&!g_flipCandidate&&M15Acceptance()){g_flipCandidate=true;Print("SMC V6.3: accepted original-zone invalidation -> FLIP_CANDIDATE. No instant reverse entry.");}MqlRates r[];ArraySetAsSeries(r,true);if(CopyRates(_Symbol,PERIOD_M1,0,480,r)<160)return;datetime cb=r[1].time;if(cb==g_lastTradeBar)return;double a=ATR(r,ATRPeriod,1);if(a<=0)return;MqlTick tk;if(!SymbolInfoTick(_Symbol,tk))return;string localRegime=TZ_LocalRegime(r);g_tzLastLocalRegime=localRegime;bool origBuy=(g_plan.original_direction=="BUY"),flipBuy=(g_plan.flip_direction=="BUY");Signal sig;ZeroMemory(sig);string tag="";bool useFlip=false,altModel=false;double share=0;if(!g_flipCandidate){if(g_primaryEntries==0&&!AnyOurPosition()){if(BuildPrimary(r,a,origBuy,sig)){tag="P0";share=PrimaryRiskShare;}else if(TZ_TryAlternativePrimary(r,a,origBuy,localRegime,sig,tag)){share=PrimaryRiskShare*AltModelRiskMultiplier;altModel=true;}}else if(EnableReentries&&g_reentries<MaxReentriesPerThesis&&AllProtected()&&!ObjectiveReached(false,origBuy,origBuy?tk.bid:tk.ask)){if(BuildReentry(r,a,origBuy,sig)){tag="R"+IntegerToString(g_reentries+1);share=(g_reentries==0?Reentry1RiskShare:Reentry2RiskShare);}else if(TZ_TryAlternativeReentry(r,a,origBuy,localRegime,sig,tag)){share=(g_reentries==0?Reentry1RiskShare:Reentry2RiskShare)*AltModelRiskMultiplier;altModel=true;}}}else if(EnableZoneFlip&&!AnyOurPosition()){useFlip=true;if(g_flipPrimaryEntries==0&&BuildFlip(r,a,flipBuy,sig)){tag="F0";share=PrimaryRiskShare;}}else if(EnableZoneFlip&&g_flipPrimaryEntries>0&&EnableReentries&&g_flipReentries<MaxReentriesPerThesis&&AllProtected()&&!ObjectiveReached(true,flipBuy,flipBuy?tk.bid:tk.ask)){useFlip=true;if(BuildReentry(r,a,flipBuy,sig)){sig.flip=true;tag="FR"+IntegerToString(g_flipReentries+1);share=(g_flipReentries==0?Reentry1RiskShare:Reentry2RiskShare);}}if(!sig.valid)return;double entry=sig.buy?tk.ask:tk.bid;if(!EntryAtValue(sig.buy,entry,sig,a))return;string seq=g_plan.analysis_id+"|"+tag+"|"+IntegerToString((int)r[sig.break_idx].time)+"|"+sig.pd_type;if(seq==g_lastSequence)return;double sl=sig.buy?sig.anchor_price-a*SLBufferATR:sig.anchor_price+a*SLBufferATR;sl=NormalizeDouble(sl,_Digits);entry=NormalizeDouble(entry,_Digits);double risk=ThesisBudget(useFlip)*share;double lots=LotsForRisk(entry,sl,risk);if(lots<=0)return;if(SendOrders(sig.buy,entry,sl,lots,useFlip,tag,sig.pd_type)){if(useFlip){if(sig.reentry)g_flipReentries++;else g_flipPrimaryEntries++;}else{if(sig.reentry)g_reentries++;else g_primaryEntries++;}g_lastSequence=seq;g_lastTradeBar=cb;g_tzLastModel=sig.pd_type;Print("SMC V6.3 ",tag," opened. regime=",localRegime," cloudRegime=",g_tzCloudRegime," model=",sig.pd_type," alt=",altModel," entry=",entry," sl=",sl," riskMoney=",risk);}}

int OnInit(){int rc=TZ_SeqCore_OnInit();if(rc!=INIT_SUCCEEDED)return rc;if(AltModelRiskMultiplier<=0||AltModelRiskMultiplier>1.0)return INIT_PARAMETERS_INCORRECT;if(MomentumRetraceMin<=0||MomentumRetraceMax>=1||MomentumRetraceMin>=MomentumRetraceMax)return INIT_PARAMETERS_INCORRECT;TZ_PreCoreSync();TZ_LoadExecutionProfile();TZ_SavePersistentState();TZ_WriteSequenceState();TZ_SendSequenceHeartbeat();Print("TradeZone Sequence runtime ",TZ_SEQUENCE_VERSION," active: SMC location + regime + ICT/Momentum/VWAP/ORB execution.");return INIT_SUCCEEDED;}
void OnDeinit(const int reason){TZ_SavePersistentState();TZ_WriteSequenceState();TZ_SeqCore_OnDeinit(reason);}
void OnTimer(){TZ_PreCoreSync();TZ_SeqCore_OnTimer();TZ_LoadExecutionProfile();TZ_LoadPersistentState();TZ_SavePersistentState();TZ_WriteSequenceState();TZ_SendSequenceHeartbeat();}
void OnTick(){TZ_PreCoreSync();ManagePositions();Evaluate();TZ_SavePersistentState();TZ_WriteSequenceState();TZ_SendSequenceHeartbeat();}
